# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.http.grpc import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInstitutions = channel.unary_unary(
                '/semantic.SemanticService/GetInstitutions',
                request_serializer=service__pb2.InstitutionReq.SerializeToString,
                response_deserializer=service__pb2.InstitutionsResp.FromString,
                _registered_method=True)
        self.AddInstitution = channel.unary_unary(
                '/semantic.SemanticService/AddInstitution',
                request_serializer=service__pb2.Institution.SerializeToString,
                response_deserializer=service__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.GetAuthors = channel.unary_unary(
                '/semantic.SemanticService/GetAuthors',
                request_serializer=service__pb2.AuthorReq.SerializeToString,
                response_deserializer=service__pb2.AuthorsResp.FromString,
                _registered_method=True)
        self.AddAuthor = channel.unary_unary(
                '/semantic.SemanticService/AddAuthor',
                request_serializer=service__pb2.Author.SerializeToString,
                response_deserializer=service__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/semantic.SemanticService/GetChatHistory',
                request_serializer=service__pb2.HistoryReq.SerializeToString,
                response_deserializer=service__pb2.HistoryResp.FromString,
                _registered_method=True)
        self.CreateNewChat = channel.unary_unary(
                '/semantic.SemanticService/CreateNewChat',
                request_serializer=service__pb2.Chat.SerializeToString,
                response_deserializer=service__pb2.ChatResp.FromString,
                _registered_method=True)
        self.UpdateChat = channel.unary_unary(
                '/semantic.SemanticService/UpdateChat',
                request_serializer=service__pb2.UpdateChatReq.SerializeToString,
                response_deserializer=service__pb2.ChatResp.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/semantic.SemanticService/DeleteChat',
                request_serializer=service__pb2.DeleteChatReq.SerializeToString,
                response_deserializer=service__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.GetUserChats = channel.unary_unary(
                '/semantic.SemanticService/GetUserChats',
                request_serializer=service__pb2.UserChatsReq.SerializeToString,
                response_deserializer=service__pb2.ChatsResp.FromString,
                _registered_method=True)
        self.GetAuthorPapers = channel.unary_unary(
                '/semantic.SemanticService/GetAuthorPapers',
                request_serializer=service__pb2.AuthorPaperReq.SerializeToString,
                response_deserializer=service__pb2.PapersResponse.FromString,
                _registered_method=True)
        self.SearchPaper = channel.unary_unary(
                '/semantic.SemanticService/SearchPaper',
                request_serializer=service__pb2.SearchRequest.SerializeToString,
                response_deserializer=service__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.AddPaper = channel.unary_unary(
                '/semantic.SemanticService/AddPaper',
                request_serializer=service__pb2.AddRequest.SerializeToString,
                response_deserializer=service__pb2.PaperResponse.FromString,
                _registered_method=True)
        self.CreateMySubmission = channel.unary_unary(
                '/semantic.SemanticService/CreateMySubmission',
                request_serializer=service__pb2.CreateMySubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.UpdateMySubmission = channel.unary_unary(
                '/semantic.SemanticService/UpdateMySubmission',
                request_serializer=service__pb2.UpdateMySubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.DeleteMySubmission = channel.unary_unary(
                '/semantic.SemanticService/DeleteMySubmission',
                request_serializer=service__pb2.DeleteMySubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.GetMySubmission = channel.unary_unary(
                '/semantic.SemanticService/GetMySubmission',
                request_serializer=service__pb2.GetMySubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.ListMySubmissions = channel.unary_unary(
                '/semantic.SemanticService/ListMySubmissions',
                request_serializer=service__pb2.ListMySubmissionsRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionListResponse.FromString,
                _registered_method=True)
        self.SubmitMySubmission = channel.unary_unary(
                '/semantic.SemanticService/SubmitMySubmission',
                request_serializer=service__pb2.SubmitMySubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.ListModerationQueue = channel.unary_unary(
                '/semantic.SemanticService/ListModerationQueue',
                request_serializer=service__pb2.ListModerationQueueRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionListResponse.FromString,
                _registered_method=True)
        self.GetModerationSubmission = channel.unary_unary(
                '/semantic.SemanticService/GetModerationSubmission',
                request_serializer=service__pb2.GetModerationSubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.UpdateModerationSubmission = channel.unary_unary(
                '/semantic.SemanticService/UpdateModerationSubmission',
                request_serializer=service__pb2.UpdateModerationSubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.ModerateSubmission = channel.unary_unary(
                '/semantic.SemanticService/ModerateSubmission',
                request_serializer=service__pb2.ModerateSubmissionRequest.SerializeToString,
                response_deserializer=service__pb2.SubmissionResponse.FromString,
                _registered_method=True)


class SemanticServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInstitutions(self, request, context):
        """End
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddInstitution(self, request, context):
        """End
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAuthor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNewChat(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChat(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChats(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorPapers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPaper(self, request, context):
        """Done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPaper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMySubmissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModerationQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModerationSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModerationSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModerateSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInstitutions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstitutions,
                    request_deserializer=service__pb2.InstitutionReq.FromString,
                    response_serializer=service__pb2.InstitutionsResp.SerializeToString,
            ),
            'AddInstitution': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInstitution,
                    request_deserializer=service__pb2.Institution.FromString,
                    response_serializer=service__pb2.ErrorResponse.SerializeToString,
            ),
            'GetAuthors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthors,
                    request_deserializer=service__pb2.AuthorReq.FromString,
                    response_serializer=service__pb2.AuthorsResp.SerializeToString,
            ),
            'AddAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAuthor,
                    request_deserializer=service__pb2.Author.FromString,
                    response_serializer=service__pb2.ErrorResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=service__pb2.HistoryReq.FromString,
                    response_serializer=service__pb2.HistoryResp.SerializeToString,
            ),
            'CreateNewChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewChat,
                    request_deserializer=service__pb2.Chat.FromString,
                    response_serializer=service__pb2.ChatResp.SerializeToString,
            ),
            'UpdateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChat,
                    request_deserializer=service__pb2.UpdateChatReq.FromString,
                    response_serializer=service__pb2.ChatResp.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=service__pb2.DeleteChatReq.FromString,
                    response_serializer=service__pb2.ErrorResponse.SerializeToString,
            ),
            'GetUserChats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChats,
                    request_deserializer=service__pb2.UserChatsReq.FromString,
                    response_serializer=service__pb2.ChatsResp.SerializeToString,
            ),
            'GetAuthorPapers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorPapers,
                    request_deserializer=service__pb2.AuthorPaperReq.FromString,
                    response_serializer=service__pb2.PapersResponse.SerializeToString,
            ),
            'SearchPaper': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPaper,
                    request_deserializer=service__pb2.SearchRequest.FromString,
                    response_serializer=service__pb2.ChatMessage.SerializeToString,
            ),
            'AddPaper': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPaper,
                    request_deserializer=service__pb2.AddRequest.FromString,
                    response_serializer=service__pb2.PaperResponse.SerializeToString,
            ),
            'CreateMySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMySubmission,
                    request_deserializer=service__pb2.CreateMySubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'UpdateMySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMySubmission,
                    request_deserializer=service__pb2.UpdateMySubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'DeleteMySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMySubmission,
                    request_deserializer=service__pb2.DeleteMySubmissionRequest.FromString,
                    response_serializer=service__pb2.ErrorResponse.SerializeToString,
            ),
            'GetMySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMySubmission,
                    request_deserializer=service__pb2.GetMySubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'ListMySubmissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMySubmissions,
                    request_deserializer=service__pb2.ListMySubmissionsRequest.FromString,
                    response_serializer=service__pb2.SubmissionListResponse.SerializeToString,
            ),
            'SubmitMySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMySubmission,
                    request_deserializer=service__pb2.SubmitMySubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'ListModerationQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModerationQueue,
                    request_deserializer=service__pb2.ListModerationQueueRequest.FromString,
                    response_serializer=service__pb2.SubmissionListResponse.SerializeToString,
            ),
            'GetModerationSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModerationSubmission,
                    request_deserializer=service__pb2.GetModerationSubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'UpdateModerationSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModerationSubmission,
                    request_deserializer=service__pb2.UpdateModerationSubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
            'ModerateSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.ModerateSubmission,
                    request_deserializer=service__pb2.ModerateSubmissionRequest.FromString,
                    response_serializer=service__pb2.SubmissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic.SemanticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semantic.SemanticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInstitutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetInstitutions',
            service__pb2.InstitutionReq.SerializeToString,
            service__pb2.InstitutionsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddInstitution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/AddInstitution',
            service__pb2.Institution.SerializeToString,
            service__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetAuthors',
            service__pb2.AuthorReq.SerializeToString,
            service__pb2.AuthorsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/AddAuthor',
            service__pb2.Author.SerializeToString,
            service__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetChatHistory',
            service__pb2.HistoryReq.SerializeToString,
            service__pb2.HistoryResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNewChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/CreateNewChat',
            service__pb2.Chat.SerializeToString,
            service__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/UpdateChat',
            service__pb2.UpdateChatReq.SerializeToString,
            service__pb2.ChatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/DeleteChat',
            service__pb2.DeleteChatReq.SerializeToString,
            service__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetUserChats',
            service__pb2.UserChatsReq.SerializeToString,
            service__pb2.ChatsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthorPapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetAuthorPapers',
            service__pb2.AuthorPaperReq.SerializeToString,
            service__pb2.PapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/SearchPaper',
            service__pb2.SearchRequest.SerializeToString,
            service__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/AddPaper',
            service__pb2.AddRequest.SerializeToString,
            service__pb2.PaperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/CreateMySubmission',
            service__pb2.CreateMySubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/UpdateMySubmission',
            service__pb2.UpdateMySubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/DeleteMySubmission',
            service__pb2.DeleteMySubmissionRequest.SerializeToString,
            service__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetMySubmission',
            service__pb2.GetMySubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMySubmissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/ListMySubmissions',
            service__pb2.ListMySubmissionsRequest.SerializeToString,
            service__pb2.SubmissionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitMySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/SubmitMySubmission',
            service__pb2.SubmitMySubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModerationQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/ListModerationQueue',
            service__pb2.ListModerationQueueRequest.SerializeToString,
            service__pb2.SubmissionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModerationSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/GetModerationSubmission',
            service__pb2.GetModerationSubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModerationSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/UpdateModerationSubmission',
            service__pb2.UpdateModerationSubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModerateSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic.SemanticService/ModerateSubmission',
            service__pb2.ModerateSubmissionRequest.SerializeToString,
            service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
